### PR TITLE
update dataset to 2015 September 18

### PR DESCRIPTION
**Pull request by leandro-lugaresi**
Updates all 3 data sets with the latest updates (2015, September 18).

### CODE REVIEW

**Comment by eriksencosta** [comment]
I hope Anatel don't find a need for a tenth digit.

**Comment by henriquemoody** [comment]
We all do

**Comment by eriksencosta** [comment]
Mr Moody! Long time, man!

**Comment by henriquemoody** [comment]
I'm still alive! (or sort of :stuck_out_tongue_closed_eyes:)

**Pull request merged**
